
import java.awt.Color;
import java.awt.GridLayout;
import javax.swing.JLabel;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Christoph Mautner
 */
public class ClockGUI extends javax.swing.JFrame
{
    
    
    /**
     * Creates new form ClockGUI
     */
    public ClockGUI()
    {
        initComponents();
        this.setSize((80*8)+60, (194*3)+(50*3)+30);
        this.setLayout(new GridLayout(6, 1));
        
        ClockPanel clockpanel1 = new ClockPanel();
        ClockPanel clockpanel2 = new ClockPanel("Africa/Harare");
        ClockPanel clockpanel3 = new ClockPanel("Australia/Sydney");
        
        //Label für Localeuhrzeit
            JLabel local = new JLabel();
            local.setOpaque(true);
            local.setHorizontalAlignment(JLabel.CENTER);
            local.setForeground(Color.white);
            local.setText("Lokale Uhrzeit:");
            local.setFont(local.getFont().deriveFont(45f));
            local.setSize((80*8)+60, 50);
            local.setBackground(Color.BLACK);
        //Label für Stadtname
            JLabel africa = new JLabel();
            africa.setOpaque(true);
            africa.setHorizontalAlignment(JLabel.CENTER);
            africa.setForeground(Color.white);
            africa.setText("Uhrzeit in Africa/Harare:");
            africa.setFont(africa.getFont().deriveFont(45f));
            africa.setSize((80*8)+60, 50);
            africa.setBackground(Color.BLACK); 
        //Label für Stadtname
            JLabel toto = new JLabel();
            toto.setOpaque(true);
            toto.setHorizontalAlignment(JLabel.CENTER);
            toto.setForeground(Color.white);
            toto.setText("Uhrzeit in Australia/Sydney:");
            toto.setFont(toto.getFont().deriveFont(45f));
            toto.setSize((80*8)+60, 50);
            toto.setBackground(Color.BLACK);
        
        this.add(local);
        this.add(clockpanel1);
        this.add(africa);
        this.add(clockpanel2);
        this.add(toto);
        this.add(clockpanel3);
        
        Thread clock1 = new Thread(clockpanel1);
        clock1.start();
        Thread clock2 = new Thread(clockpanel2);
        clock2.start();
        Thread clock3 = new Thread(clockpanel3);
        clock3.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 109, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClockGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClockGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClockGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClockGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new ClockGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
